version: "3"
services:
    client:
        image: livinghopemd
        restart: always
        container_name: livinghopemd
        ports:
            - "4000:3000"
        environment:
            LETSENCRYPT_EMAIL: david.williams110913@gmail.com
            LETSENCRYPT_HOST: test.livinghopemd.dtwilliams10.com
            VIRTUAL_HOST: test.livinghopemd.dtwilliams10.com
        volumes:
            - ./client:/client
            - /client/node_modules